#!/bin/sh
# Chore Coin — test license key generator.
#
# Generates one or more random Chore Coin license keys in the format
# CHRC-XXXX-XXXX-XXXX-XXXX where each X is A-Z or 0-9.
#
# Usage:
#   scripts/generate-license.sh                        # one key, no label
#   scripts/generate-license.sh "Cousin Sarah"         # one key, with label
#   scripts/generate-license.sh -n 5                   # 5 keys
#   scripts/generate-license.sh -n 3 -f keys.txt       # 3 keys, append to file
#
# During v0 (before Lemon Squeezy integration + Ed25519 signature
# verification lands), Chore Coin accepts any format-valid key. That means
# these keys work as real license keys — perfect for handing out free copies
# to family + beta testers, but ALSO means keys are trivially forgeable
# and you shouldn't publish them anywhere public.
#
# When Lemon Squeezy integration lands, we'll switch to real signed keys.
# The keys generated by this script won't have valid signatures then and
# will need to be replaced (or the customer's install will need a bypass
# for beta-issued keys — we'll figure that out at cutover time).
#
# Tracking suggestion: keep a private note somewhere (a notes app, a
# Notion/Obsidian file, a private repo — anything NOT public) with entries
# like:
#     CHRC-A7X4-9K2M-QP3R-B8YN   Sarah + Mike (cousins)   issued 2026-08-12
#     CHRC-J5NP-M2WQ-K7X8-C9LR   Priya (beta tester)      issued 2026-08-14
# When Lemon Squeezy is live, migrate these entries into real purchases
# (or gift them a real key via a Lemon Squeezy comp).

set -eu

COUNT=1
LABEL=""
OUTFILE=""

# --- arg parsing (POSIX getopts) ---
while getopts "n:f:h" opt; do
	case "$opt" in
		n) COUNT="$OPTARG" ;;
		f) OUTFILE="$OPTARG" ;;
		h)
			sed -n '2,40p' "$0" | sed 's/^# \?//'
			exit 0
			;;
		*) exit 2 ;;
	esac
done
shift $((OPTIND - 1))
if [ $# -gt 0 ]; then
	LABEL="$*"
fi

# --- validate count ---
case "$COUNT" in
	*[!0-9]*|"") echo "Error: -n must be a positive integer" >&2 ; exit 2 ;;
esac
[ "$COUNT" -gt 0 ] || { echo "Error: -n must be > 0" >&2 ; exit 2 ; }
[ "$COUNT" -le 100 ] || { echo "Error: refusing to generate more than 100 keys at once" >&2 ; exit 2 ; }

# --- generator: 16 uppercase alphanumeric chars from /dev/urandom ---
# Uses tr with the C locale to avoid multibyte-locale glitches on macOS.
gen_key() {
	CHARS=$(LC_ALL=C tr -dc 'A-Z0-9' < /dev/urandom | head -c 16)
	# POSIX sh doesn't have string slicing; use cut instead.
	G1=$(printf "%s" "$CHARS" | cut -c1-4)
	G2=$(printf "%s" "$CHARS" | cut -c5-8)
	G3=$(printf "%s" "$CHARS" | cut -c9-12)
	G4=$(printf "%s" "$CHARS" | cut -c13-16)
	printf "CHRC-%s-%s-%s-%s" "$G1" "$G2" "$G3" "$G4"
}

# --- emit ---
TODAY=$(date -u +%Y-%m-%d)
i=1
while [ "$i" -le "$COUNT" ]; do
	KEY=$(gen_key)
	if [ -n "$LABEL" ]; then
		LINE="$KEY   $LABEL   issued $TODAY"
	else
		LINE="$KEY   issued $TODAY"
	fi
	if [ -n "$OUTFILE" ]; then
		printf "%s\n" "$LINE" >> "$OUTFILE"
	fi
	printf "%s\n" "$LINE"
	i=$((i + 1))
done

if [ -n "$OUTFILE" ]; then
	echo
	echo "Appended $COUNT key(s) to $OUTFILE."
fi
